### ISSUE TITLE
CP2102 multi-function module驱动安装不成功

### ISSUE THREAD

**Issue by MrJianglc** [Livox-SDK/livox_high_precision_mapping#4]
我在安装你们推荐的USB to TTL/RS232 module：CP2102 multi-function module的时候，驱动安装不成功（驱动地址：https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers）。我的操作系统是Ubuntu16.04。驱动安装的使用说明上写的驱动是：“This driver has only been written and tested on the Linux 3.13.0 kernel on Ubuntu 14.04. This driver is a modified version of the existing driver in the Linux 3.13.0 kernel, which is maintained at kernel.org”。我不确定16.04是否适用。

按照驱动的按照指引：第一步"1. make ( your cp210x driver )"，可以正常完成。但是第二步"cp cp210x.ko to /lib/modules/<kernel-version>/kernel/drivers/usb/serial",我在我的操作系统中找不到/lib/modules/<kernel-version>/kernel/drivers下的USB文件夹

Terminal下的操作如下：
dji@manifold2:/lib/modules/4.4.38+/kernel/drivers$ pwd
/lib/modules/4.4.38+/kernel/drivers
dji@manifold2:/lib/modules/4.4.38+/kernel/drivers$ ls
ata  media  misc  mtd  net  pci  video
dji@manifold2:/lib/modules/4.4.38+/kernel/drivers$

**Comment by Livox-SDK** [comment]
Hi, Ubuntu 16.04 of Manifold2 has CP2102 driver, needn't reinstall.
