### ISSUE TITLE
How did you measure the accuracy of 2cm?

### ISSUE THREAD

**Issue by congphase** [Livox-SDK/livox_high_precision_mapping#9]
Hi all,

I find myself really interested in this project. I'm handling problems regarding mapping and autonomous driving HD maps in general.

I'm wondering how you measured the accuracy, i.e 2cm?

I'm kind of new to the mapping problem. So if anyone of you coming across this question, please help clarify this for me.

Thank you a lot.

**Comment by Livox-SDK** [comment]
Hi congphase,
I think you can use higher precision equipment to poof the accuracy,
